name: Release Debug APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for this release'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Create Release
        id: create_release
        run: |
          gh release create ${{ github.event.inputs.tag }} \
            --title "Release ${{ github.event.inputs.tag }}" \
            --notes "Release notes for ${{ github.event.inputs.tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug-v${{ github.event.inputs.tag }}.apk
          asset_content_type: application/vnd.android.package-archive
